{
  "result": "compile_failed",
  "message": "/tmp/tmp5hu2005s/src/ut_assert/src/uttest.c: In function 'UtTest_Run':\n/tmp/tmp5hu2005s/src/ut_assert/src/uttest.c:321:53: error: 'UtAssert_TestCounter_t' has no member named 'Failed'\n  321 |                     (unsigned)UtAssert_GetCounters()->Failed, (unsigned)UtAssert_GetCounters()->Passed,\n      |                                                     ^~\n/tmp/tmp5hu2005s/src/ut_assert/src/uttest.c:321:95: error: 'UtAssert_TestCounter_t' has no member named 'Passed'\n  321 |                     (unsigned)UtAssert_GetCounters()->Failed, (unsigned)UtAssert_GetCounters()->Passed,\n      |                                                                                               ^~\ngmake[2]: *** [ut_assert/CMakeFiles/ut_assert.dir/build.make:118: ut_assert/CMakeFiles/ut_assert.dir/src/uttest.c.o] Error 1\ngmake[1]: *** [CMakeFiles/Makefile2:788: ut_assert/CMakeFiles/ut_assert.dir/all] Error 2\ngmake: *** [Makefile:146: all] Error 2"
}